# from turtle import*
# title ( "Spécialité ISN" )
# forward(120)
# left(90)
# color("red")
# forward(90)
# circle ( 20 )
# circle ( -20 )
# dot(20,"blue")
# setheading(0)
# forward(80)
# dot(15,'green')
# setheading(270)
# up()
# forward(80)
# down()
# dot(30,"pink")
# up()
# forward(30)
# down()
# circle(40,180)
# color('black')
# goto(100,-100)
# write('THE END')
# mainloop()

def square() :
    forward(50)
    left(90)
    forward(50)
    left(90)
    forward(50)
    left(90)
    forward(50)
from turtle import *

square ()
up()
mainloop()